# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [closed]
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install -g vsce
      - run: yarn
      - run: vsce publish -p $AZURE_TOKEN
        env:
          AZURE_TOKEN: ${{secrets.AZURE_TOKEN}}

  tag:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const path = require('path');
            const pkg = require(path.resolve('package.json'))
            const version = pkg.version;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const tag = await github.git.createTag({
                owner,
                repo,
                tag:version,
                message:`release version ${version}`,
                object:context.sha,
                type:'commit',
            });
            const tagref = await github.git.createRef({
              owner,
              repo,
              ref:`refs/tags/${version}`,
              sha:tag.data.sha,
            })
